# https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/
log:
  level: DEBUG

api:
  insecure: true  # since we want a secure api service accessible via https
  dashboard: true

# traefik will only listen to incoming requests on port 443
entryPoints:
  web:
    address: ":80" 

providers:
  docker:
    # when false, requires adding traekik.enabled=true
    # label to containers we want traefik to see
    exposedbydefault: false
